/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.MenuControl;
import control.PesananControl;
import control.PesawatControl;
import exception.BandaraSamaException;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JOptionPane;
import model.Pesanan;
import model.Menu;
import model.Pesawat;


/**
 *
 * @author Gde Rama Vedanta Yudhistira \n 200710735
 */
public class DetailPesananView extends javax.swing.JFrame {
    private int id;
    int total;
    int bagasi;
    /**
     * Creates new form DetailPesananView
     */
    PesawatControl pesawatControl;
    PesananControl pesananControl;
    MenuControl menuControl;
    List<Pesanan> listPesanan;
    List<Menu> listMenu;
    Pesanan ps;
    
    
    public DetailPesananView() {
        initComponents();
    }
    public DetailPesananView(int id) {
        this.id = id;
        initComponents();
        
        pesananControl = new PesananControl();
        pesawatControl = new PesawatControl();
        menuControl = new MenuControl();
        
        Pesanan psn = pesananControl.searchPesanan(id);
        
        if(psn.getMenu() != null)
        setMenuDd();
        setLabel();
    }
    
    public void setTotalLabel(){
        labelTotal1.setText("Rp. "+total);
    }
    
    public void countTotal(){
        total = ps.getPesawat().getHarga() * ps.getJumlah_penumpang();
        if(bagasiInput.getText().length() > 0)
        total += Integer.parseInt( bagasiInput.getText().toString()) * 20000;
    }
    
    public void setMenuDd(){
        listMenu = menuControl.showListMenu();
        for (int i = 0; i < listMenu.size(); i++) {
            cbMenu.addItem(listMenu.get(i));
        }
    }
    
    public void setLabel(){
        ps = pesananControl.searchPesanan(id);
        lblNama.setText(ps.getNama_pemesan());
        lblTiket.setText(ps.getNo_tiket());
        lblAsal.setText(ps.getPesawat().getAsal().getNama());
        lblTujuan.setText(ps.getPesawat().getTujuan().getNama());
        lblKelas.setText(ps.getPesawat().getKelas());
        lblPenumpang.setText(String.valueOf(ps.getJumlah_penumpang()));
        lblTanggal.setText(ps.getTanggal());
        listMenu = menuControl.showListMenu();
        total = ps.getTotal();
        bagasi = ps.getBagasi();
        bagasiInput.setText(bagasi+"");
        labelTotal1.setText("Rp. "+total);
        for (Menu menu : listMenu) {
            if(menu.getNama().equals(ps.getMenu().getNama()))
                cbMenu.setSelectedItem(menu);
        }
    }

    public void InputKosongException() throws InputKosongException{
        if(bagasiInput.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    
    public void NumberException() throws NumberFormatException{
        if(bagasiInput.getText().length() > 0)
        Integer.parseInt(bagasiInput.getText().toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        BandaraPanel = new javax.swing.JPanel();
        lecturerIcon = new javax.swing.JLabel();
        lecturerLabel = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        courseIcon = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        TiketPanel = new javax.swing.JPanel();
        lecturerIcon1 = new javax.swing.JLabel();
        lecturerLabel1 = new javax.swing.JLabel();
        PesawatPanel = new javax.swing.JPanel();
        lecturerIcon3 = new javax.swing.JLabel();
        lecturerLabel3 = new javax.swing.JLabel();
        PesananPanel = new javax.swing.JPanel();
        lecturerIcon2 = new javax.swing.JLabel();
        lecturerLabel2 = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleContent = new javax.swing.JLabel();
        searchBtn1 = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchBtn2 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        matakuliahLabel1 = new javax.swing.JLabel();
        matakuliahLabel2 = new javax.swing.JLabel();
        matakuliahLabel3 = new javax.swing.JLabel();
        matakuliahLabel4 = new javax.swing.JLabel();
        matakuliahLabel5 = new javax.swing.JLabel();
        matakuliahLabel6 = new javax.swing.JLabel();
        matakuliahLabel7 = new javax.swing.JLabel();
        cbMenu = new javax.swing.JComboBox<>();
        bagasiInput = new javax.swing.JTextField();
        matakuliahLabel8 = new javax.swing.JLabel();
        lblTiket = new javax.swing.JLabel();
        labelTotal1 = new javax.swing.JLabel();
        matakuliahLabel9 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblAsal = new javax.swing.JLabel();
        lblTujuan = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblPenumpang = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(22, 52, 122));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        sidebarPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BandaraPanel.setBackground(new java.awt.Color(22, 52, 122));
        BandaraPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BandaraPanelMouseClicked(evt);
            }
        });

        lecturerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/bandara.png"))); // NOI18N

        lecturerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lecturerLabel.setForeground(new java.awt.Color(255, 255, 255));
        lecturerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerLabel.setText("Data Bandara");

        javax.swing.GroupLayout BandaraPanelLayout = new javax.swing.GroupLayout(BandaraPanel);
        BandaraPanel.setLayout(BandaraPanelLayout);
        BandaraPanelLayout.setHorizontalGroup(
            BandaraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BandaraPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BandaraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lecturerLabel)
                    .addComponent(lecturerIcon))
                .addContainerGap())
        );
        BandaraPanelLayout.setVerticalGroup(
            BandaraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BandaraPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lecturerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lecturerLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        sidebarPanel.add(BandaraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 283, -1, -1));

        MenuPanel.setBackground(new java.awt.Color(7, 24, 89));
        MenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPanelMouseClicked(evt);
            }
        });

        courseIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/menu.png"))); // NOI18N

        courseLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        courseLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseLabel.setText("Data Menu");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(courseIcon)
                    .addComponent(courseLabel))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebarPanel.add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 190, 110, -1));

        TiketPanel.setBackground(new java.awt.Color(22, 52, 122));
        TiketPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TiketPanelMouseClicked(evt);
            }
        });

        lecturerIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/tiket.png"))); // NOI18N

        lecturerLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lecturerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        lecturerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerLabel1.setText("Pesan Tiket");

        javax.swing.GroupLayout TiketPanelLayout = new javax.swing.GroupLayout(TiketPanel);
        TiketPanel.setLayout(TiketPanelLayout);
        TiketPanelLayout.setHorizontalGroup(
            TiketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TiketPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TiketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lecturerIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lecturerLabel1))
                .addContainerGap())
        );
        TiketPanelLayout.setVerticalGroup(
            TiketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TiketPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lecturerIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lecturerLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarPanel.add(TiketPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 100, 100, -1));

        PesawatPanel.setBackground(new java.awt.Color(22, 52, 122));
        PesawatPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesawatPanelMouseClicked(evt);
            }
        });

        lecturerIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/pesawat.png"))); // NOI18N

        lecturerLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lecturerLabel3.setForeground(new java.awt.Color(255, 255, 255));
        lecturerLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerLabel3.setText("Data Pesawat");

        javax.swing.GroupLayout PesawatPanelLayout = new javax.swing.GroupLayout(PesawatPanel);
        PesawatPanel.setLayout(PesawatPanelLayout);
        PesawatPanelLayout.setHorizontalGroup(
            PesawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesawatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PesawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lecturerLabel3)
                    .addComponent(lecturerIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PesawatPanelLayout.setVerticalGroup(
            PesawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesawatPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lecturerIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lecturerLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        sidebarPanel.add(PesawatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 379, -1, -1));

        PesananPanel.setBackground(new java.awt.Color(22, 52, 122));
        PesananPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesananPanelMouseClicked(evt);
            }
        });

        lecturerIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/pesanan.png"))); // NOI18N

        lecturerLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lecturerLabel2.setForeground(new java.awt.Color(255, 255, 255));
        lecturerLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerLabel2.setText("Data Pesanan");

        javax.swing.GroupLayout PesananPanelLayout = new javax.swing.GroupLayout(PesananPanel);
        PesananPanel.setLayout(PesananPanelLayout);
        PesananPanelLayout.setHorizontalGroup(
            PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesananPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lecturerIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerLabel2))
                .addContainerGap())
        );
        PesananPanelLayout.setVerticalGroup(
            PesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesananPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lecturerIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lecturerLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        sidebarPanel.add(PesananPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 475, -1, -1));

        containerPanel.setBackground(new java.awt.Color(243, 243, 243));

        headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

        titleContent.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        titleContent.setText("Detail Pesanan");

        searchBtn1.setBackground(new java.awt.Color(22, 52, 122));
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("Refund");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 52, 122));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Tambah Bagasi");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchBtn2.setBackground(new java.awt.Color(22, 52, 122));
        searchBtn2.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn2.setText("Ubah Menu");
        searchBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleContent)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(searchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn2)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(searchBtn1)
                    .addComponent(searchBtn2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(22, 52, 122));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        matakuliahLabel1.setText("Nama Pemesan");

        matakuliahLabel2.setText("Jumlah Penumpang");

        matakuliahLabel3.setText("Kelas");

        matakuliahLabel4.setText("Asal");

        matakuliahLabel5.setText("Tujuan");

        matakuliahLabel6.setText("Tanggal");

        matakuliahLabel7.setText("Menu");

        bagasiInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bagasiInputKeyReleased(evt);
            }
        });

        matakuliahLabel8.setText("Bagasi");

        lblTiket.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        lblTiket.setText("(no tiket)");

        labelTotal1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        labelTotal1.setText("Rp. 0");

        matakuliahLabel9.setText("No tiket");

        lblNama.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblNama.setText("Nama Pemesan");

        lblAsal.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblAsal.setText("Nama Pemesan");

        lblTujuan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTujuan.setText("Nama Pemesan");

        lblKelas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblKelas.setText("Nama Pemesan");

        lblPenumpang.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblPenumpang.setText("Nama Pemesan");

        lblTanggal.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTanggal.setText("Nama Pemesan");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(lblTiket)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(matakuliahLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                    .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(matakuliahLabel1)
                                        .addComponent(matakuliahLabel4)
                                        .addComponent(matakuliahLabel5)
                                        .addComponent(matakuliahLabel3))
                                    .addGap(187, 187, 187))
                                .addComponent(matakuliahLabel7)
                                .addComponent(cbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNama)
                            .addComponent(lblAsal)
                            .addComponent(lblTujuan)
                            .addComponent(lblKelas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matakuliahLabel6)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bagasiInput, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(matakuliahLabel8))
                                .addGroup(contentPanelLayout.createSequentialGroup()
                                    .addComponent(saveBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(cancelBtn)))
                            .addComponent(lblPenumpang)
                            .addComponent(lblTanggal)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelTotal1)
                                .addComponent(matakuliahLabel2)))
                        .addGap(76, 76, 76))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(matakuliahLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTiket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTotal1)
                        .addGap(21, 21, 21)))
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(matakuliahLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPenumpang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(matakuliahLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(matakuliahLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagasiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn)
                            .addComponent(saveBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(matakuliahLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matakuliahLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(lblAsal)
                        .addGap(18, 18, 18)
                        .addComponent(matakuliahLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(lblTujuan)
                        .addGap(18, 18, 18)
                        .addComponent(matakuliahLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKelas)
                        .addGap(21, 21, 21)
                        .addComponent(matakuliahLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BandaraPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BandaraPanelMouseClicked
        // TODO add your handling code here:
        BandaraView view = new BandaraView();
        this.dispose();
        view.setVisible(true);
    }//GEN-LAST:event_BandaraPanelMouseClicked

    private void MenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPanelMouseClicked
        // TODO add your handling code here:
        MenuView view = new MenuView();
        this.dispose();
        view.setVisible(true);
    }//GEN-LAST:event_MenuPanelMouseClicked

    private void TiketPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TiketPanelMouseClicked
        // TODO add your handling code here:
        PesananView view = new PesananView();
        this.dispose();
        view.setVisible(true);
    }//GEN-LAST:event_TiketPanelMouseClicked

    private void PesawatPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesawatPanelMouseClicked
        // TODO add your handling code here:
        PesawatView view = new PesawatView();
        this.dispose();
        view.setVisible(true);
    }//GEN-LAST:event_PesawatPanelMouseClicked

    private void PesananPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananPanelMouseClicked
        // TODO add your handling code here:
        TiketView view = new TiketView();
        this.dispose();
        view.setVisible(true);
    }//GEN-LAST:event_PesananPanelMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try {
            InputKosongException();
            
            ps.setBagasi(Integer.parseInt(bagasiInput.getText().toString()));
            if(ps.getPesawat().getKelas().equalsIgnoreCase("bisnis"))
                ps.setMenu(listMenu.get(cbMenu.getSelectedIndex()));            
            pesananControl.updateDataPesanan(ps,ps.getId());
            
            JOptionPane.showMessageDialog(this, "Pesanan Berhasil diubah");

            setLabel();
            cbMenu.setEnabled(false);
            bagasiInput.setEnabled(false);

        } catch (InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        bagasiInput.setEnabled(true);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void bagasiInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bagasiInputKeyReleased
        // TODO add your handling code here:
        NumberException();
        countTotal();
        setTotalLabel();
    }//GEN-LAST:event_bagasiInputKeyReleased

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin refund ?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
            try{
                pesananControl.deleteDataPesanan(ps.getId());
                Pesawat pt = ps.getPesawat();
                pt.setKapasitas(pt.getKapasitas() + ps.getJumlah_penumpang());
                pesawatControl.updateDataPesawat(pt, pt.getId());
                PesananView view = new PesananView();
                this.dispose();
                view.setEnabled(true);
            } catch (Exception e){
                System.out.println("Error : " + e.getMessage());
            }
            break;
            case 1:

            break;
        }
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void searchBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn2ActionPerformed
        // TODO add your handling code here:
        cbMenu.setEnabled(true);
    }//GEN-LAST:event_searchBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPesananView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BandaraPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PesananPanel;
    private javax.swing.JPanel PesawatPanel;
    private javax.swing.JPanel TiketPanel;
    private javax.swing.JTextField bagasiInput;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<Menu> cbMenu;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel courseIcon;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel labelTotal1;
    private javax.swing.JLabel lblAsal;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPenumpang;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTiket;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JLabel lecturerIcon;
    private javax.swing.JLabel lecturerIcon1;
    private javax.swing.JLabel lecturerIcon2;
    private javax.swing.JLabel lecturerIcon3;
    private javax.swing.JLabel lecturerLabel;
    private javax.swing.JLabel lecturerLabel1;
    private javax.swing.JLabel lecturerLabel2;
    private javax.swing.JLabel lecturerLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel matakuliahLabel1;
    private javax.swing.JLabel matakuliahLabel2;
    private javax.swing.JLabel matakuliahLabel3;
    private javax.swing.JLabel matakuliahLabel4;
    private javax.swing.JLabel matakuliahLabel5;
    private javax.swing.JLabel matakuliahLabel6;
    private javax.swing.JLabel matakuliahLabel7;
    private javax.swing.JLabel matakuliahLabel8;
    private javax.swing.JLabel matakuliahLabel9;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JButton searchBtn2;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel titleContent;
    // End of variables declaration//GEN-END:variables
}
